### ISSUE TITLE
TypeError: Cannot read property 'message' of null

### ISSUE THREAD

**Issue by aventurella** [IonicaBizau/git-stats#103]
When trying to import using the -e flag I get the following error:

```
/Users/aventurella/github/project/node_modules/gitlog-parser/index.js:37
      this._current.message += ('\n'+chunk);

TypeError: Cannot read property 'message' of null
    at Gitlog._write (/Users/aventurella/github/project/node_modules/gitlog-parser/index.js:37:20)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Gitlog.Writable.write (_stream_writable.js:220:11)
    at LineStream.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:96:13)
    at LineStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at LineStream.Readable.push (_stream_readable.js:135:10)
    at LineStream.Transform.push (_stream_transform.js:128:32)
```

**Comment by IonicaBizau** [comment]
That looks like an issue in `gitlog-parser`. Is the repo public? /cc @yorkie

**Comment by aventurella** [comment]
No, unfortunately the repo is not public.

**Comment by yorkie** [comment]
@aventurella may I ask you to `console.log(chunk+'')` and post your result here? It seems like your commit message is invalid that have no first line :)

**Comment by aventurella** [comment]
I am including the `chunk` from line 33 and line 37. 

I can -e with an email I end up at line 37, and I can -e with another name not an email and I end up at line 33.

Line 33 (no email):
```
Fri Nov 18 16:38:09 2016 -0800 5e7a105 (HEAD -> dev) chore(web): edit startup output  [Adam Venturella]
```

Line 37 (via email):
```
Fri Nov 18 15:59:30 2016 +0000 9cd6fbf Merge pull request #124 in PROJECT/web from feature/thing to dev  [Adam Venturella (Contractor)]
```

**Comment by aventurella** [comment]
I know what it is...

In my ~/.gitconfig I have my format set

```
[format]
      pretty = format:%C(blue)%ad%Creset %C(yellow)%h%C(green)%d%Creset %C(blue)%s %C(magenta) [%an]%Creset
```

When I turn this off it fixes it.

**Comment by yorkie** [comment]
Yup, thus can removing gitconfig fix your problem so that we could close this issue?

**Comment by IonicaBizau** [comment]
I guess it'll be better to use an option in the `git log` command to use the default config. There should be one, I just don't know how it should look like. :grin:

**Comment by aventurella** [comment]
Yup, i think it's safe to close the issue. It might just be worth mentioning this in the docs.

**Comment by yorkie** [comment]
:)
