### ISSUE TITLE
Is there any method to git-stats --record some records from an JSON api?

### ISSUE THREAD

**Issue by cmal** [IonicaBizau/git-stats#104]
Hi, I've implemented an api FreeCodeCamp/FreeCodeCamp#11650
of FreeCodeCamp to output stats in the format of
```
{
  stats: {
    username: "fcccc4f8191",
    stats: [
      {
        date: 1479552008474,
        hash: "6dedf981ecab9ce1b3f997508dcb796f90838328"
      },
      {
        date: 1479619115285,
        hash: "051284a491a053ba29896deaf7a49f17ade241c1"
      },
      {
        date: 1479619250135,
        hash: "3aa47ee34e5bab839c88bfb411f1946e84253fea"
      }
    ]
  }
}
```
Is there any method to import it to git-stats? If not, would you mind me to make a pull request to implement one?

**Comment by IonicaBizau** [comment]
You should be able make a script (maybe it can be another module/cli app) which will use `git-stats` as a module. You'll be able to use the [`record`](https://github.com/IonicaBizau/git-stats/blob/master/DOCUMENTATION.md#recorddata-callback) method and convert the `date` timestamp into a `Date` object you can pass to it.

```js
// Dependencies
var GitStats = require("../lib");

// Create the GitStats instance
var gs = new GitStats();

var inputData = {
  stats: {
    username: "fcccc4f8191",
    stats: [{
      date: 1479552008474,
      hash: "6dedf981ecab9ce1b3f997508dcb796f90838328"
    }, {
      date: 1479619115285,
      hash: "051284a491a053ba29896deaf7a49f17ade241c1"
    }, {
      date: 1479619250135,
      hash: "3aa47ee34e5bab839c88bfb411f1946e84253fea"
    }]
  }
};

gs.get(function(err, stats) {
  var finalData = stats;
  inputData.stats.stats.forEach(c => {
    gs.record({
      date: new Date(c.date),
      save: false,
      hash: c.hash,
      _data: stats
    }, function() {});
  });
  gs.save(finalData);
});
```

I didn't test it, maybe it already works (but I don't think so :grin:). Let me know if you have any questions.

Note that the documentation has some mistakes in it.

Have fun!

**Comment by cmal** [comment]
Thanks for your help.

**Comment by IonicaBizau** [comment]
@cmal Let me know how it goes. Later we can add your script/module/cli app to the documentation so other people can easily find it. :grin:

**Comment by IonicaBizau** [comment]
@cmal Just fixed the `require` call (it should be `require("git-stats")`, not `../lib`).

**Comment by cmal** [comment]
With the help of you, I've written a small cli tool https://github.com/cmal/git-stats-fcc-importer , but still wait FreeCodeCamp's api pull request FreeCodeCamp/FreeCodeCamp#11723 to be active.  @IonicaBizau I'll publish to npm soon after the pull request being accepted.

**Comment by IonicaBizau** [comment]
@cmal Amazing! 😁
