### ISSUE TITLE
`git-stats-html` cannot read raw data if `git-stats` specifies `-g`

### ISSUE THREAD

**Issue by cmal** [IonicaBizau/git-stats#105]
```
1246 ± : git-stats -s '1 January 2012' -u '18 November 2016' -g --raw|git-stats-html -o out.html --big                                                                                                                                                              [22h7m] ✖ ✹
/usr/local/lib/node_modules/.git-stats-html_npminstall/node_modules/.1.0.1@git-stats-html/lib/index.js:26
    json.levels.forEach(function (c, weekIndex) {
               ^

TypeError: Cannot read property 'forEach' of undefined
    at gitStatsHtml (/usr/local/lib/node_modules/.git-stats-html_npminstall/node_modules/.1.0.1@git-stats-html/lib/index.js:26:16)
    at Tilda.main.action (/usr/local/lib/node_modules/.git-stats-html_npminstall/node_modules/.1.0.1@git-stats-html/bin/git-stats-html:35:5)
    at emitOne (events.js:96:13)
    at Tilda.emit (events.js:188:7)
    at Tilda.parse (/usr/local/lib/node_modules/.git-stats-html_npminstall/node_modules/.4.4.2@tilda/lib/index.js:575:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/.git-stats-html_npminstall/node_modules/.4.4.2@tilda/lib/index.js:330:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

```
Sorry I'm not quite understand what `global-activity` means. 😄

**Comment by cmal** [comment]
I found that the keys of json output of `git-stats --raw` is
[ 'total',
  'days',
  'cStreak',
  'lStreak',
  'max',
  'longestStreak',
  'currentStreak',
  'data',
  'theme',
  'start',
  'end',
  'levels' ]
and the keys of json output of `git-stats --raw -g` is
[ 'theme', 'start', 'end', 'cal' ]

**Comment by IonicaBizau** [comment]
Ah, good catch. It's because of [this check](https://github.com/IonicaBizau/git-stats/blob/988895afef607f26e603329a52e1ae41a333e420/lib/index.js#L663).

Here we need to return the `CliGhCal` output, not `data`.

**Comment by cmal** [comment]
@IonicaBizau Hi, sorry to bother. May I ask you a question? I do not understand what `global-activity` actually means, and why here we need to return the CliGhCal output, not data. Thank you!

**Comment by IonicaBizau** [comment]
The global activity graph renders the commit stats for *all* the contributors of the repository.

**Comment by cmal** [comment]
I see.. thank you for your kind!

**Comment by IonicaBizau** [comment]
```sh
git-stats -g -s '1 January 2015' -r | git-stats-html --big > out.html
```

Creates the following:

![image](https://cloud.githubusercontent.com/assets/2864371/22217732/dcf69124-e1ac-11e6-9262-107adbf6a284.png)

Same thing, but in the terminal:

![image](https://cloud.githubusercontent.com/assets/2864371/22217770/f5eb661e-e1ac-11e6-8bf4-5a2839a8d511.png)

Enjoy! :tada:
