### ISSUE TITLE
Git hook installed to wrong location

### ISSUE THREAD

**Issue by neutrinog** [IonicaBizau/git-stats#113]
my git templates are located in `~/.dotfiles/git/templates/` however when I ran the script to set up the hook (`curl -s https://raw.githubusercontent.com/IonicaBizau/git-stats/master/scripts/init-git-post-commit | bash`) it installed it to `~/~/.dotfiles/git/templates/hooks/` notice the extra ~/.

Even though the script "says" that is installed it to the correct location (without extra ~/).

**Comment by IonicaBizau** [comment]
Hmm, looks like a bug!

It should be somewhere here: https://github.com/IonicaBizau/git-stats/blob/aabf6dd33771df42a468c0a866bd13afae9d6b60/scripts/init-git-post-commit#L15-L22

What does this command output for you?

```sh
git config --global --get init.templatedir
```

**Comment by neutrinog** [comment]
That gives the correct location. `~/.dotfiles/git/templates`

**Comment by IonicaBizau** [comment]
What about this:

```sh
git_templates_dir=$(git config --global --get init.templatedir);
git_hooks_dir="${git_templates_dir}/hooks"
post_commit_path="${git_hooks_dir}/post-commit"
echo $git_hooks_dir
echo post_commit_path
```

Eventually save it in a file and run it as a bash script.

**Comment by neutrinog** [comment]
you left off a `$` ;)

```
~/.dotfiles/git/templates/hooks
~/.dotfiles/git/templates/hooks/post-commit
```

**Comment by neutrinog** [comment]
it almost seems like `mkdir -p` is not resolving the ~/

**Comment by IonicaBizau** [comment]
@neutrinog Whoups, that sounds interesting!

**Comment by neutrinog** [comment]
ok so `mkdir "~"` will create a new directory since ~ is surrounded in quotes. I'll bet you anything that it's because `$git_hooks_dir` is a string.

**Comment by IonicaBizau** [comment]
@neutrinog So, we will have to use absolute paths, probably. Or maybe is there an option for `mkdir` to resolve the `~`?

**Comment by neutrinog** [comment]
@IonicaBizau it seems like you may be able to do something like this:

```
echo ~/.dotfiles/git/templates
/home/joel/.dotfiles/templates
```

Perhaps you can grab the output of an echo to get the expanded path?

**Comment by IonicaBizau** [comment]
Interesting that `echo ~` outputs the home directory path. :grin: I didn't know that.

I'm not sure: was this fixed in the end or what is the state of this issue?
