### ISSUE TITLE
No commit found

### ISSUE THREAD

**Issue by trosh** [IonicaBizau/git-stats#115]
git-stats shows an empty history in a repo with 40 commits from the past month.

Installed on Arch Linux from the AUR (https://aur.archlinux.org/packages/node-gitstats) using Yaourt.

**Comment by trosh** [comment]
https://aur.archlinux.org/packages/nodejs-git-stats

**Comment by IonicaBizau** [comment]
Did you import the existing commits using the importer?

https://github.com/IonicaBizau/git-stats#importing-and-deleting-commits

**Comment by trosh** [comment]
Haha reading the README helps

Moving oooon

**Comment by IonicaBizau** [comment]
😁
