### ISSUE TITLE
Add TERM=st-256color support

### ISSUE THREAD

**Issue by trosh** [IonicaBizau/git-stats#116]
`git-stat` should behave the same way with `TERM` set to `st-256color` as for `xterm-256color` (and `screen-256color`, though with different escape codes).

**Comment by IonicaBizau** [comment]
It should be available already, but I pushed a quick fix due to a bug from a dependency: https://github.com/IonicaBizau/git-stats/blob/aabf6dd33771df42a468c0a866bd13afae9d6b60/bin/git-stats#L4

By removing that line (since the bug was fixed), this very issue should be fixed too.
