### ISSUE TITLE
Option `first_day` doesn't work

### ISSUE THREAD

**Issue by blvz** [IonicaBizau/git-stats#121]
It's [ignored by the binary](https://github.com/IonicaBizau/git-stats/blob/6aca8214ac831d7fb12c6e9fb539105963e1b651/bin/git-stats#L137-L141) and [overridden by cli-gh-cal](https://github.com/IonicaBizau/cli-gh-cal/blob/91058167560c96fa7394d9f3a76f69b746e2e946/lib/index.js#L126).

By manually changing the value, day labels are changed, but the squares stays the same:

![git-stats-firstday-issue](https://cloud.githubusercontent.com/assets/134438/26151553/c43fefdc-3ad9-11e7-8a52-b4ad1b54273d.png)

**Comment by IonicaBizau** [comment]
This option was deprecated. /cc #99 

Probably we should remove the references from the docs. 📝

**Comment by miriti** [comment]
So is there a way to make the first day Monday now?

**Comment by IonicaBizau** [comment]
@miriti No, that's not possible. The feature was buggy, and instead of investing time to fix it, I though it's better to remove it.
