### ISSUE TITLE
git-stats does not show any data

### ISSUE THREAD

**Issue by zbug** [IonicaBizau/git-stats#131]
Hi,

$ git-stats on my master branch returns: 
![image](https://user-images.githubusercontent.com/1159758/34222054-82f1d662-e5ba-11e7-89f6-0dad59276af3.png)

However, running
$ git-stats -g returns 
![image](https://user-images.githubusercontent.com/1159758/34222081-9ebf54dc-e5ba-11e7-9308-1f9e4f58017b.png)

What is blocking git-stats from reading my contributions? I am highly active in this repo from this computer/user.

**Comment by IonicaBizau** [comment]
You may need to import your previous commits, like documented here: https://github.com/IonicaBizau/git-stats#importing-and-deleting-commits
