### ISSUE TITLE
[Support] git-stats raw data interpretation

### ISSUE THREAD

**Issue by tryadelion** [IonicaBizau/git-stats#135]
Hi, i have to tell you that this project is awesome.
i would like to know a few things, though:
what is the levels array for in the raw data?
is there a way to explode the data array to get to see who did each commit?
is there a way to get commit information?
is there a way to make the days array date more parse-friendly?
does the data come from *every git project imported using git-stats import*, or does it come from the project where the command is run at? ( i suppose #.2, but i want to be sure)
i see there's a contributors graph, but there's no contributor data on the json, where can i get it?
i'm planning evil stuff to gamify the office and personal projects a bit and this would come reaaally handy, so kudos for this project.

**Comment by IonicaBizau** [comment]
The store file is `~/.git-stats`. You can use that file to create other graphs. I hope this helps!
