### ISSUE TITLE
Small squares

### ISSUE THREAD

**Issue by sg-s** [IonicaBizau/git-stats#14]
like this:

![screen shot 2015-02-16 at 10 01 11 am](https://cloud.githubusercontent.com/assets/6005346/6213936/c60b2a96-b5c2-11e4-91bf-b8a52084551c.png)

help?

**Comment by IonicaBizau** [comment]
It really depends on the monospaced font you use in the terminal.

What font do you use?

**Comment by sg-s** [comment]
I'm using a patched version of SourceCodePro (from [these guys](https://github.com/arialdomartini/oh-my-git)) but the font doesn't seem to be the problem. 

i tried with a bunch of different fonts, and the problem persists. e.g., here it is with monaco:

![screen shot 2015-02-16 at 10 07 18 am](https://cloud.githubusercontent.com/assets/6005346/6214037/a918262c-b5c3-11e4-8ba9-880426be11fb.png)

**Comment by IonicaBizau** [comment]
What platform/application is this?

**Comment by sg-s** [comment]
sorry, should have mentioned. Terminal on Mac OS X 10.10

**Comment by sg-s** [comment]
the `--no-ansi` flag works well:

![screen shot 2015-02-16 at 10 13 18 am](https://cloud.githubusercontent.com/assets/6005346/6214130/79fe9bc2-b5c4-11e4-9c21-af5998f2bf3c.png)

so I guess this issue is not a big deal for me (though it is a bug). thanks for your help!

**Comment by sg-s** [comment]
@IonicaBizau what font do you use?

**Comment by IonicaBizau** [comment]
See the screenshot:

![image](https://cloud.githubusercontent.com/assets/2864371/6248591/c6d9b9ce-b789-11e4-9f45-9422e8b344a4.png)

On Ubuntu, I use Monaco. I suppose that something is wrong with the `■` character on different platforms.

**Comment by sg-s** [comment]
thanks, it works with `Menlo`, but unfortunately that breaks other things.

**Comment by IonicaBizau** [comment]
*other things* being...?

**Comment by sg-s** [comment]
this git [prompt](https://github.com/arialdomartini/oh-my-git)

**Comment by IonicaBizau** [comment]
Instead of changing the font, probably I will consider to change the square character since I see this is an issue on Windows too: https://github.com/IonicaBizau/git-stats/issues/19#issuecomment-74719551 (there it's displayed `?`).

**Comment by IonicaBizau** [comment]
Really hope this was finally fixed! :ship: 1.6.0

**Comment by sg-s** [comment]
thanks for fixing this!

**Comment by IonicaBizau** [comment]
@sg-s Does it work fine? :smile: I hope so! You're welcome. :+1:

**Comment by sg-s** [comment]
yup, it's great now!
