### ISSUE TITLE
configuring git-stats

### ISSUE THREAD

**Issue by Snotzer** [IonicaBizau/git-stats#141]
Hi,

Its not very clear from the readme how to configure git-stats.
I followed the install instructions on a linux machine but when I execute git-stats in a git repo or anywhere for that matter. It returns an empty calendar.

From reading the code installed in /usr/lib/node_modules/git-stats I see a post-commit hook method is used to call git-stats --record "...". Im not familiar with javascript or npm. Do I need to add this post-commit script to new/existing git repos? 

I also tried executing git-stats-importer but it didn't seem to do anything?

Best regards

Damian

**Comment by IonicaBizau** [comment]
See: https://github.com/IonicaBizau/git-stats#importing-all-the-commits-from-github-and-bitbucket
