### ISSUE TITLE
bash: git-stats: command not found

### ISSUE THREAD

**Issue by owenstrevor** [IonicaBizau/git-stats#144]
After following instructions from #95 my installation still does not work.

After running 

`source ~/.bashrc`

I got the following error

> nvm is not compatible with the npm config "prefix" option: currently set to "/Users/Owens/.node"
> Run `npm config delete prefix` or `nvm use --delete-prefix v7.2.1 --silent` to unset it.

**Comment by IonicaBizau** [comment]
If you use `nvm`, you simply need to do `npm i -g git-stats`.
