### ISSUE TITLE
Feature wish: Lines of code

### ISSUE THREAD

**Issue by mg98** [IonicaBizau/git-stats#145]
I would like to see an option to see the lines of code added/ deleted by contributor.

**Comment by iamdriz** [comment]
I would also like to see this an option. Number of commits doesn't really give a clear insight as someone could of replaced the entire codebase with 1 commit and yet the stats would say they had contributed the least amount.

**Comment by IonicaBizau** [comment]
This goes a bit outside of the main point of this project, so I am going to close this for now. But however, if someone has a clear intention in how this can be implemented, we can discuss it eventually. Thanks!
