### ISSUE TITLE
Show daily hours of activity over week

### ISSUE THREAD

**Issue by hyiltiz** [IonicaBizau/git-stats#154]
Currently, what's plotted is `weekday vs. months` within a year. 
Feature request: provide an option to plot `weekday vs. hours` within a week (averaging all weeks), in the commit's Time Zone (so 12:00 is noon and 23:59 is almost midnight for the *developer* submitting the commit).

**Comment by IonicaBizau** [comment]
I think this would be outside of the scope of the project, but using the ``--json`` output, you would have the data needed to build custom graphs like that.
