### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by sabreofsd** [IonicaBizau/git-stats#156]
Trying to install this on RH 7 (unfortunately what I am stuck on).  Here is the error I recevie:

![image](https://user-images.githubusercontent.com/1273629/80116792-66671480-8554-11ea-9a00-4cde96147fc9.png)

NPM version 6.14.4
Node 12.16.2

**Comment by c0dezer019** [comment]
I get this error as well
NPM version: 6.14.8
Node version: 14.15.1

**Comment by IonicaBizau** [comment]
Duplicate of #169
