### ISSUE TITLE
Empty stats

### ISSUE THREAD

**Issue by message** [IonicaBizau/git-stats#16]
I cloned my github repo and it shows zero stats... What am i doing wrong?
![screenshot from 2015-02-16 17 27 02](https://cloud.githubusercontent.com/assets/492026/6214431/27c709b0-b601-11e4-9ba0-673349a9315e.png)

**Comment by IonicaBizau** [comment]
First import them:

```sh
$ npm install -g git-stats-importer
$ git-stats-importer
```

**Comment by IonicaBizau** [comment]
See this: https://github.com/IonicaBizau/git-stats#importing-and-deleting-commits :book:
