### ISSUE TITLE
Not able to see any of my own contributions

### ISSUE THREAD

**Issue by tbarlow12** [IonicaBizau/git-stats#160]
For every repo I have, I see the same stats:

![image](https://user-images.githubusercontent.com/10962815/95743958-6dd7c280-0c47-11eb-8c09-26152a0ad6a3.png)

Is there some trick that I missed for configuring `git-stats` to show the current user's contributions?

**Comment by colin4124** [comment]
use `git-stats -g`

**Comment by IonicaBizau** [comment]
For a local repository you will have to use `git-stats -g` like @colin4124 mentioned.
