### ISSUE TITLE
Aggregate a user

### ISSUE THREAD

**Issue by hrpomrx** [IonicaBizau/git-stats#164]
Could you possibly add a way to treat 2 users as one? Due to having set a different user name somewhere in the recent past, I'm seeing myself as a user named "Firstname Lastname" but also as another named "Lastname, Firstname" and I'd like to combine the stats for these two without having to revise the user name in past commits. It could be as simple as a config file containing a list of user names to be aggregated/treated as one.

**Comment by IonicaBizau** [comment]
The `.mailmap` features can be used to alias the users globally.
