### ISSUE TITLE
Formatting breaks when using `watch`

### ISSUE THREAD

**Issue by jonalmeida** [IonicaBizau/git-stats#17]
If you were to use `watch git-stats`, which calls the same command (i.e. `git-stats`) after a set interval of time, you should be able to see the stats graph update as changes are made.

Instead, there is a formatting issue that only shows you strange (unicode?) characters across your terminal. See image below:
![screenshot from 2015-02-16 12 27 20](https://cloud.githubusercontent.com/assets/1370580/6216349/5a44b3bc-b5d7-11e4-8751-9e0e1cd691d4.png)

**Comment by IonicaBizau** [comment]
This is not a bug but it is the intended behavior. 

`watch` doesn't allow colors by default, however `watch --color` should do it. It didn't worked properly for me (maybe it doesn't allow 256 colors?), and that's why I used the following workaround:

```sh
while true; do clear; git-stats; sleep 2; done
```

(modify `2` in the number of seconds of the interval)

Give me feedback if this worked.

**Comment by jonalmeida** [comment]
`watch --color` did indeed show the stats but you can't see the colors which makes all "days" look the same (another screenshot below). The while-loop method causes a flash at every interval when refreshing but it does still work.

Cool stuff regardless!

![screenshot from 2015-02-16 12 53 27](https://cloud.githubusercontent.com/assets/1370580/6216798/33680574-b5db-11e4-90d9-84a6b62da0e9.png)

**Comment by IonicaBizau** [comment]
OK, you should be able to do this with the [`regarde`](https://github.com/IonicaBizau/regarde) tool, which I have just published:

```sh
$ npm install -g regarde
$ regarde 'git-stats' # 1 second interval
$ regarde 'git-stats' -n 10 # 10 seconds
```

**Comment by jonalmeida** [comment]
Fantastic, It works great now! I've been playing with it by importing repos individually and it seems to work well :)

Thanks for crazy fast support!

Closing..

**Comment by IonicaBizau** [comment]
You're welcome! :smile: Glad it's working!
