### ISSUE TITLE
File filter

### ISSUE THREAD

**Issue by ruslan-voodoo** [IonicaBizau/git-stats#176]
Hey!

I couldn't find any file filter. I'm working with the Unity game engine and there is a lot of metafiles and asset files that are not related to code and in the pie chart, there is a lot of noise because of this. Would be great to set filter like -f '.cs' to see actual code contribution and not when someone moved sprite to 1 pixel or changes font size:)

**Comment by IonicaBizau** [comment]
`.gitignore` should do the trick — as long the the file is tracked by git, it will count in the contributions. However pull requests are welcomed to improve this!
