### ISSUE TITLE
The pie chart drops top contributors from the legend if there are more than 40

### ISSUE THREAD

**Issue by RijnBuve-TomTom** [IonicaBizau/git-stats#178]
The pie chart seems to drop top contributors from the legend if there are more than 40 contributors in total.

**Comment by DenverCoder1** [comment]
Yeah, I'm noticing this as well

![image](https://user-images.githubusercontent.com/20955511/160513955-b4a808d6-5a05-43e9-9797-604b941c277d.png)

It seems to only show the lowest contributors (~1% of contributions) when there are contributors who should have a much more significant amount (seems like up to 25%)

**Comment by DenverCoder1** [comment]
Related: #126
