### ISSUE TITLE
Sunday is not the first day everywhere :)

### ISSUE THREAD

**Issue by grigouze** [IonicaBizau/git-stats#18]
Is it possible to begin the stats as Monday ?

**Comment by IonicaBizau** [comment]
[Here](https://github.com/IonicaBizau/git-stats/blob/4e9258955f6cfbf6d480b9288ddc8480cc36fb5b/lib/index.js#L315) instead of `Sun` it should be `Mon`.

Do you have any idea how the configuration should look like?

**Comment by IonicaBizau** [comment]
See #57. :smile: This will be closed when `v2.0.0` will be merged.
