### ISSUE TITLE
Calendar doesn't seem to work correctly on Windows.

### ISSUE THREAD

**Issue by mrboomer** [IonicaBizau/git-stats#19]
As someone who uses Windows at work, I tried git-stats and it only logs the days on the calendar by highlighting the day, but does not show the density of commits.

The default cmd font, 'raster font', displays rectangles instead of squares. Changing the font to either 'Consolas' or 'Lucida Console' does display square boxes, but still does not show density of commits.
![raster-font](https://cloud.githubusercontent.com/assets/5942912/6233180/0b3992ba-b686-11e4-9d36-d7055c05e58f.jpg)
(Using CMD with 'Raster Font')

Using 'Git Bash', the calendar seems to overflow outside it's boundaries as well.
![consolas](https://cloud.githubusercontent.com/assets/5942912/6233207/2d110ba2-b686-11e4-84fc-6087c4d06882.jpg)
(Using 'Git Bash' with 'Consolas')

**Comment by IonicaBizau** [comment]
Yep, I didn't test it on Windows...

Can you check the output of `git-stats --no-ansi`?

**Comment by mrboomer** [comment]
Using 'cmd'
![raster-font](https://cloud.githubusercontent.com/assets/5942912/6234104/dd471344-b68c-11e4-9ca7-ceaa9ab37e33.jpg)
(with default 'Raster Font')

![lucida_console](https://cloud.githubusercontent.com/assets/5942912/6234109/ed21b7f6-b68c-11e4-89af-23a330276407.jpg)
(with 'Lucida Console')


Using 'Git Bash'
![bash_lucida_console](https://cloud.githubusercontent.com/assets/5942912/6234164/63abfac6-b68d-11e4-9917-a8ff9b73155a.jpg)
(with 'Lucida Console')

The output looks the same on 'Git Bash' as it does 'cmd' when using default 'Raster Font'.

**Comment by mrboomer** [comment]
Note: When I mention 'Git Bash', I mean I am using 'Git for Windows':
http://msysgit.github.io/

**Comment by IonicaBizau** [comment]
I will debug these things in a virtual machine. However, if somebody is faster than me, contributions are welcome! :smile:

**Comment by IonicaBizau** [comment]
This is documented now in the README.md–use a terminal emulator which supports ANSI styles. :dizzy:
