### ISSUE TITLE
error Error: ENOENT, open '~/.git-stats'

### ISSUE THREAD

**Issue by ionelmc** [IonicaBizau/git-stats#2]
I get this when running git-stats:

```
error Error: ENOENT, open '/home/ionel/.git-stats'
```

Seems it doesn't create this file. What's going on here?

Details
```
$ node --version
v0.10.33
```

**Comment by IonicaBizau** [comment]
Yeah, that's an bug... 

We should check here if the file doesn't exists: https://github.com/IonicaBizau/git-stats/blob/c70ecec82ea1a5b0d9ab6bf3094097b4d74a54bf/lib/index.js#L98

If so, it should be created:

```js
if (err && err.code === "ENOENT") {
   return GitStats.save({}, function (err) {
       callback(err, {});
   });
}
```

I'd appreciate a pull request with this change! Thanks! :smile: 

In the mean time you can fix it quickly by running `echo '{}' > ~/.git-stas`.

**Comment by ionelmc** [comment]
Ah yeah, I did that then I realized I need to override the git commit command in my shell.

Any way to import the history? (I don't use the `git commit` command anyway).

**Comment by IonicaBizau** [comment]
@ionelmc This is for you: https://github.com/IonicaBizau/git-stats#importing-and-deleting-commits :package: :gift: :smile:

**Comment by atuttle** [comment]
`npm docs git-stats-importer` (it's kind of buried in the readme, took me a while to find it too)

**Comment by IonicaBizau** [comment]
@atuttle  +1 for `npm docs`, something that I was looking for! :smile:
