### ISSUE TITLE
Bad month labels positionning

### ISSUE THREAD

**Issue by as0n** [IonicaBizau/git-stats#21]
Current month labels positionning in the output is somewhat random and does not always appear nicely above the corresponding week columns.

![git-stats-importer](https://cloud.githubusercontent.com/assets/3386177/6235335/0c2004b4-b6e2-11e4-9cfe-0399a5500575.png "Example : "Aug" is shifted to the left and "Feb" starts one week early.")

It would be neat to position the month labels right above the first week of the month.

I wrote a patch for this and I'm gonna post a pull request asap.

**Comment by IonicaBizau** [comment]
Thanks for bringing this here. This can is even worse for a longer period:

```sh
$ git-stats '1 January 2012'
```

**Comment by IonicaBizau** [comment]
Fixed in `1.3.0` via #23.
