### ISSUE TITLE
Please add support for remotes other than origin

### ISSUE THREAD

**Issue by eveliotc** [IonicaBizau/git-stats#22]
We don't use `origin`, we name all of our remotes differently, trying to import I get `error Cannot find the remote origin url. Please add it.`

![No origin](http://i.imgur.com/txXoVvo.png)

**Comment by IonicaBizau** [comment]
This should be fixed via `git-stats-importer@1.5.0`:

```sh
$ npm install git-stats-importer@latest
$ git-stats-importer
```

**Comment by philadams** [comment]
Just a note: if you set up the post-commit hook, that script also errors on an invalid url field.... I suspect the same bug is at play.

**Comment by IonicaBizau** [comment]
@philadams Wohups, good point. It should be updated here: https://github.com/IonicaBizau/git-stats/blob/6b4d38b6f1696f1642dca73ee2517012e7630f11/scripts/init-git-post-commit#L15

...and maybe with a cross platform command...

**Comment by philadams** [comment]
:+1:
