### ISSUE TITLE
number of columns not calculated correctly

### ISSUE THREAD

**Issue by floriankrueger** [IonicaBizau/git-stats#24]
When executing git-stats, the number of columns expected by the tool is always 1 bigger than the actual number of columns available (in the example the console has 100 columns, but the output fits into 101 columns). Changing the number of columns beforehand didn't change anything. Is there something that I'm missing as nobody else has this problem?

![screen shot 2015-02-18 at 08 39 11](https://cloud.githubusercontent.com/assets/646386/6243797/befe9f0c-b749-11e4-8787-e1c18e97c989.png)

**Comment by IonicaBizau** [comment]
See this discussion: https://github.com/IonicaBizau/ghcal/issues/1

And yes, it's a bug. :+1:

**Comment by floriankrueger** [comment]
ah I see, it works totally fine w/ 113 columns (or even 112 in --no-ansi mode) and I'm fine with that. thank you for the pointer and sorry I didn't see it. :smiley:

**Comment by IonicaBizau** [comment]
Cool, but like I commented there, we have to make it better... Maybe displaying `...` in the left side.

**Comment by philadams** [comment]
Do note that whatever's going when the `--no-ansi` flag is passed corrects this, for basically any number of columns. So a quick local patch until @IonicaBizau is able to fix this bug is to just alias `git-stats` to `git-stats --no-ansi`.

Looks better in some of my weird iTerm2/tmux color schemes anyway!

**Comment by philadams** [comment]
Though that does appear to kill the ability to pass in a 'start' parameter like '1 January 2015'.

**Comment by IonicaBizau** [comment]
This should be fixed now via https://github.com/IonicaBizau/cli-gh-cal/pull/12.

`npm i -g ghcal@latest` should be enough. :tada:
