### ISSUE TITLE
Windows Error: Cannot find the remote origin url. Please add it.

### ISSUE THREAD

**Issue by charlieWasp** [IonicaBizau/git-stats#26]
Hello! Thank you for the great tool you made. I've installed it on my Mac, and it's awesome. Unfortunately there is Windows on my work laptop, and there I've got this sad message:

```
> git-stats-importer
error Cannot find the remote origin url. Please add it.
```

My .git/config file looks like this:
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	hideDotFiles = dotGitOnly
[remote "origin"]
	url = git@bitbucket.org:foo/my-repo.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

Is there something wrong?

**Comment by IonicaBizau** [comment]
This is an issue in `git-stats-importer`: https://github.com/IonicaBizau/git-stats-importer/issues/1

If you find a solution, I will be happy to accept contributions!

**Comment by IonicaBizau** [comment]
But in the mean time you can install an older version that doesn't contain this bug on Windows: `npm install -g git-stats-importer@1.4.0`.

**Comment by charlieWasp** [comment]
@IonicaBizau cool, thanks, I used 1.3.0, because npm said, that there is no 1.4.0 version :) Now it works, not so pretty, however, thank you for your reply and help!

**Comment by IonicaBizau** [comment]
This is fixed via [`git-stats-importer@1.6.0`](https://github.com/IonicaBizau/git-stats-importer/releases/tag/1.6.0), thanks to @linquize for https://github.com/IonicaBizau/git-stats-importer/pull/15.

**Comment by IonicaBizau** [comment]
@charlieWasp I'd be happy if you confirmed this works fine after `npm install -g git-stats-importer@latest`. :smile: Then we can close this issue.

**Comment by IonicaBizau** [comment]
I really hope this was fixed in https://github.com/IonicaBizau/git-stats-importer/pull/15. :smirk:
