### ISSUE TITLE
New schema prototype (2.x.x)

### ISSUE THREAD

**Issue by IonicaBizau** [IonicaBizau/git-stats#38]
I'm thinking at the `~/.git-stats` file prototype which will be implemented starting with version `2.0.0`.

```js
{
    "commits": {
       "<date>": ["628947f965..........ea9689ca747", "..."]
    },
  , "remotes": {
        "git@github.com:IonicaBizau/git-stats.git": ["git-stats-hash1", "git-stats-hash2", ... ]
      , "git@github.com:IonicaBizau/git-stats-importer.git": ["git-stats-importer-hash1", "git-stats-importer-hash2", ... ]
    }
  , "config": {
      "light": true
   }
}
```

 - `commits`: an object with dates, being arrays with unique commit hashes. 
 -  `remotes`: an object with remotes, containing arrays with unique commit hashes
 - `config`: defaults, aliases :question: 

I'm trying to cover the feedback from the following issues:

 - https://github.com/IonicaBizau/git-stats/issues/29
 - https://github.com/IonicaBizau/git-stats/issues/18
 - https://github.com/IonicaBizau/git-stats-importer/issues/1

If you have any ideas how to improve this, please leave comments here. :speech_balloon:

**Comment by Flyingmana** [comment]
sounds reasonable, but I wonder if a switch to an sqlite file for storing the commits is better in the long run. But I also dont know, from which file size on this makes sense.

**Comment by IonicaBizau** [comment]
After reaching the 3k stars milestone I will start working on the `2.0.0` version. :smile: :star2: :fireworks:

**Comment by IonicaBizau** [comment]
So, I'm planning for the next week to start the work on 2.0.0. :star2: Any suggestions, ideas you have, please share them here and we can discuss how to implement different things.

**Comment by IonicaBizau** [comment]
The `config` things are moved in `~/.git-stats-config` (see #58) for more information. :dizzy:
