### ISSUE TITLE
ignore commits with identical hash

### ISSUE THREAD

**Issue by Flyingmana** [IonicaBizau/git-stats#39]
multiple import of the same repository causes multiple entries for each commit, even if the commit IDs should be unique.

Thats only the visible problem, the true problem is, that `git-stats --record` allows to record the same commit multiple times.

Using the commit ID as unique key should solve this, maybe also add the repo.url so we avoid cross repository ID conflicts(which statistically should never happen, for the same user)

**Comment by IonicaBizau** [comment]
I couldn't reproduce this, but it's true that same commit can be recorded multiple times via `--record`, but not in the same date.

See #38 for the new schema and let's comment there with any ideas.

**Comment by IonicaBizau** [comment]
:ship: `2.0.0` :tada:
