### ISSUE TITLE
track new commits via global hook instead of git command rewrite

### ISSUE THREAD

**Issue by Flyingmana** [IonicaBizau/git-stats#4]
git has hooks, for example for commits.
They should also be globally usable, and this would be a way better entry point then to rewrite the shell commands

**Comment by atuttle** [comment]
... except that they are defined per-repo per-clone (e.g. per machine). If you work on one repo all the time, that's fine and dandy; but if you work on 50 repos (and growing all the time) that sounds like a pain in the butt to set up and keep track of.

**Comment by Flyingmana** [comment]
seems right, I wonder why there are no global hook feature, at least I dont find documentation for it.
But I find this tool which offers global git hooks https://github.com/icefox/git-hooks

**Comment by atuttle** [comment]
Still ends up requiring action in each repo, but instead of copying a file into each you now have to run CLI commands in each. Not saving too much if the only global hook you need is this one.

**Comment by IonicaBizau** [comment]
That's a good point, @Flyingmana! I was googling for global git commit hooks and I found this: https://coderwall.com/p/jp7d5q/create-a-global-git-commit-hook

Maybe it helps us. Will test it today.
