### ISSUE TITLE
Display problem in tmux

### ISSUE THREAD

**Issue by tobegit3hub** [IonicaBizau/git-stats#40]
Here's the screenshot from my gnome-terminal. It works like a charm.

![git-status-terminal](https://cloud.githubusercontent.com/assets/2715000/6390037/0b8178cc-bde4-11e4-86ad-f91278d74416.png)

But there's some problems when I execute `git-status` in tmux.

![git-status-tmux](https://cloud.githubusercontent.com/assets/2715000/6390045/1cb79b8a-bde4-11e4-990e-66ed8c850958.png)

**Comment by IonicaBizau** [comment]
I use `tmux` everyday, but this looks like you haven't enabled 256 colors in tmux.

Put this in your conf file:
```conf
set -g default-terminal "screen-256color"
```

I also [have the following in my `.bashrc`](https://github.com/IonicaBizau/dotfiles/blob/master/user/.bashrc):

```sh
export TERM=xterm-256color
```

I don't know which ones enables 256 colors, but you can try and tell me. :smile:

**Comment by tobegit3hub** [comment]
Oh, both of them don't work. It may be the problem of my Ubuntu. The tmux in my Mac OS just works like a charm without any other configuration.

**Comment by IonicaBizau** [comment]
@tobegit3hub Please post your `tmux` version (`tmux -V`). In the meantime, check if [starting tmux using `tmux -2`](http://unix.stackexchange.com/a/176048/45370) solves the problem.

**Comment by tobegit3hub** [comment]
```
➜  ~  tmux -V
tmux 1.9a
```

`tmux -2` works well like a charm even though I don't know why. Thanks :+1:

**Comment by tobegit3hub** [comment]
It may be the issue of `tmux`, not `git-stats`.

**Comment by IonicaBizau** [comment]
`tmux -2` forces `tmux` to support 256 colors. Anyway, this is definitely a `tmux` issue.

/cc @lcristianiim Any explanations why `tmux -2` fixes the problem?

**Comment by lcristianiim** [comment]
For some reason tmux can't start with 256 colors suport. On my machine I always start tmux with tmux -2.

Until now I did not find a better solution.

See:
http://unix.stackexchange.com/questions/175182/tmux-ignores-the-configuration-files
