### ISSUE TITLE
The hook installation in the readme clobbers existing hooks

### ISSUE THREAD

**Issue by ashleyblackmore** [IonicaBizau/git-stats#41]
Running the command here clobbers any existing hooks:
     curl -s https://raw.githubusercontent.com/IonicaBizau/git-stats/master/scripts/init-git-post-commit | bash

An improvement could be to make a note in the readme, or to modify the bash script to run append-only. Happy to make a PR for either.

**Comment by IonicaBizau** [comment]
Couldn't reproduce it:

```sh
onicabizau@notebook:~$ cat .git-templates/hooks/post-commit 
#!/bin/sh

echo ">>>"

### git-stats hook (begin) ###
# Copy last commit hash to clipboard on commit
commit_hash=$(git rev-parse HEAD)
repo_url=$(git config --get remote.origin.url)
commit_date=$(git log -1 --format=%cd)
commit_data="\"{ \"date\": \"$commit_date\", \"url\": \"$repo_url\", \"hash\": \"$commit_hash\" }\""
git-stats --record "${commit_data}"
### git-stats hook (end) ###

echo ">>> 1"
ionicabizau@notebook:~$ curl -s https://raw.githubusercontent.com/IonicaBizau/git-stats/master/scripts/init-git-post-commit | bash
Setting up git-stats hooks.
Successfully set up git-stats hook at /home/ionicabizau/.git-templates/hooks/post-commit.
ionicabizau@notebook:~$ cat .git-templates/hooks/post-commit 
#!/bin/sh

echo ">>>"

echo ">>> 1"
### git-stats hook (begin) ###
# Copy last commit hash to clipboard on commit
commit_hash=$(git rev-parse HEAD)
repo_url=$(git config --get remote.origin.url)
commit_date=$(git log -1 --format=%cd)
commit_data="\"{ \"date\": \"$commit_date\", \"url\": \"$repo_url\", \"hash\": \"$commit_hash\" }\""
git-stats --record "${commit_data}"
### git-stats hook (end) ###
```

It's true that `echo ">>> 1"` went to top, but it was not removed. Can you describe your usecase?

**Comment by ashleyblackmore** [comment]
Sorry, I just got around to double-checking - I was wrong - I was looking in the wrong directory (`.git-templates/hooks/`, rather than `.git/hooks/`)

**Comment by ashleyblackmore** [comment]
@IonicaBizau on a related note, I like the script, so I've adapted a bit of it my own hook and credited you in the hook comment header. However, I decided to use sed instead of perl because it is a bit cleaner. I'm on linux, so maybe sed is a better approach than perl in my case.

Anyway, an idea of what I mean:

sed '/### git-stats hook (begin) ###/,/### git-stats hook (end) ###/d' $post_commit_path > $post_commit_path

Anyway, my hook is [here](https://github.com/ashleyblackmore/beardsnapper/blob/master/setup.sh) if you want to look.

**Comment by IonicaBizau** [comment]
@ashleyblackmore Nice! :+1:
