### ISSUE TITLE
zsh: empty stats after successful import of commits

### ISSUE THREAD

**Issue by garnett** [IonicaBizau/git-stats#44]
![2015-04-19 22-42-40 1 lebedzeu lebedzeu-nb-osx src mtt latam-ios-fresh zsh](https://cloud.githubusercontent.com/assets/829783/7221049/8c53eaa0-e6e5-11e4-8600-d945a419fbaa.png)

**Comment by IonicaBizau** [comment]
I indeed need to clarify this in docs! :memo: 

However, please check this issue and see if following the steps described there will solve your problem: https://github.com/IonicaBizau/git-stats-importer/issues/21

**Comment by garnett** [comment]
My ```.gitstats``` is not empty and
```⇒  git rev-list HEAD --author=`git config user.email` --count``` returns 305 :cry:

**Comment by IonicaBizau** [comment]
@garnett Maybe they are not committed in the *last year*?

**Comment by garnett** [comment]
```
* cc9fbed      (2 days)  <Denis Lebedev>      (HEAD, origin/LP-2770, LP-2770) LP-2770: pass airline
* 6ef8126      (3 days)  <Denis Lebedev>      LP-2770: load real cms content
* 5c6cfe9      (3 days)  <Denis Lebedev>      LP-2770: add alert when user opens external link
```

**Comment by IonicaBizau** [comment]
@garnett Hmm... Looks like a bug. Could you please tell me what OS and terminal emulator are you using?

Is the repository public, so I can play with it? What's the output of `git-stats -v`?

**Comment by garnett** [comment]
zsh 5.0.5 (x86_64-apple-darwin14.0) + iTerm2

```
git-stats -v
1.4.0
```

**Comment by IonicaBizau** [comment]
> My .gitstats is not empty

@garnett Could you post somewhere the `.gitstats` file? Since it contains data, the `git-stats` tool should take data from there.

**Comment by garnett** [comment]
https://gist.github.com/garnett/339532926e59a9d42d78 here it goes. It's name ```.git-stats``` in my system, however

**Comment by IonicaBizau** [comment]
> It's name .git-stats in my system, however

Yes, that's expected.

Here is how it is supposed to appear

![screenshot from 2015-04-23 11 30 43](https://cloud.githubusercontent.com/assets/2864371/7293285/39654d60-e9ac-11e4-8a5c-70664b81538b.png)

Could you please post screenshots with the output of the following commands?

```sh
$ git-stats
$ git-stats --light
$ git-stats --no-ansi
```

If the `--no-ansi` option works fine, then most probably there is an issue with the colors.

**Comment by garnett** [comment]
Ok, I see the problem myself - it does not fit widht of my terminal :crying_cat_face: 
![2015-04-23 11-37-01 1 lebedzeu lebedzeu-nb-osx src mtt latam-ios-fresh zsh](https://cloud.githubusercontent.com/assets/829783/7293394/69c54b6c-e9ad-11e4-9883-abd66022dc43.png)
![2015-04-23 11-37-16 1 lebedzeu lebedzeu-nb-osx src mtt latam-ios-fresh zsh](https://cloud.githubusercontent.com/assets/829783/7293396/6a02d270-e9ad-11e4-924b-2674f09f6c9e.png)
![2015-04-23 11-37-28 1 lebedzeu lebedzeu-nb-osx src mtt latam-ios-fresh zsh](https://cloud.githubusercontent.com/assets/829783/7293395/6a0194aa-e9ad-11e4-90d7-78181d154775.png)

**Comment by garnett** [comment]
That what it's looks like when I make terminal window wider:
![2015-04-23 11-41-01 1 lebedzeu lebedzeu-nb-osx src mtt latam-ios-fresh zsh](https://cloud.githubusercontent.com/assets/829783/7293432/b2bfbf78-e9ad-11e4-8fe2-a77d79bae272.png)

**Comment by IonicaBizau** [comment]
I see. Then I guess this is a duplicate of #24.

For reference, see https://github.com/IonicaBizau/ghcal/issues/1.

**Comment by garnett** [comment]
Yes, it is.

**Comment by IonicaBizau** [comment]
:+1:

**Comment by IonicaBizau** [comment]
I'd like to get this fixed in the next major release.
