### ISSUE TITLE
Browser graph

### ISSUE THREAD

**Issue by IonicaBizau** [IonicaBizau/git-stats#46]
For the `2.0.0` I want to introduce some nice graphs in browser. :star2:

**Comment by fnogatz** [comment]
Just want to hint at [githubchart](https://github.com/akerl/githubchart) which might be help or inspiration.

**Comment by IonicaBizau** [comment]
:+1: Nice! Will take a closer look to that.

**Comment by IonicaBizau** [comment]
Closing this as `wontfix`. In the future I may create a different project to use the git-stats data, but this is behind the scope of this project. We want to focus on the terminal now. :smile:
