### ISSUE TITLE
Extract graph generation

### ISSUE THREAD

**Issue by fnogatz** [IonicaBizau/git-stats#49]
Thanks for the awesome tool :)
I wanted to use CLI activity graph for other data too, especially for my [clocker](https://github.com/substack/clocker) statistics. Therefore I extracted the part that generates the graph and published it as a standalone: [cli-cal](https://github.com/fnogatz/cli-cal).
Looking forward to v2.0 I would love to help separating the stats- and graph-based parts. In this way git-stats is focused on generating the stats and uses external modules to generate CLI- or browser graphs (#46). These modules can be improved as a standalone, so #14 and #28 would be solved for all kind of data.

**Comment by IonicaBizau** [comment]
Hey!

That's a very good idea. :sparkles: 
I will think what will be the workflow on this. I'd prefer to be the owner of these modules since they are linked between them and making the updating easier.

I've added this issue to the v2.0.0 milestone.

**Comment by IonicaBizau** [comment]
@fnogatz In #54 I addressed this. It's working smoothly. :smile: Thanks again for this idea.

**Comment by fnogatz** [comment]
Thanks for your efforts to implement this. I will deprecate [cli-cal@npm](https://www.npmjs.com/package/cli-cal). Let me know if you want to take the module name.

**Comment by IonicaBizau** [comment]
@fnogatz If you like, we can merge it into mine (so you don't loose your commits). `cli-cal` would be nice for a real calendar for command line, so don't unpublish it yet. :smile: I saw you handle `stdin` stream there. :four_leaf_clover:

**Comment by fnogatz** [comment]
No need to worry about another PR when your module is already of equivalent scope. I simply added a deprication notice on [cli-cal](https://github.com/fnogatz/cli-cal).

**Comment by IonicaBizau** [comment]
@fnogatz Just in case that one day you want to delete this project, feel free to merge your commits in mine project so your green squares on contributions calendar will not disappear. :smile:

**Comment by fnogatz** [comment]
You take your git-stats (harhar) quite seriously, don't you? :D
