### ISSUE TITLE
Export graph to image file

### ISSUE THREAD

**Issue by easwee** [IonicaBizau/git-stats#50]
A good feature could be to add a command to export commit graph into an image file (jpeg/png) for easy sharing.

Something like "git-stats -exporttoimage" - you name it.

**Comment by IonicaBizau** [comment]
Any package to generate images without needing some special binaries to install (e.g. `graphicsmagick`)? `graphicsmagick` is powerful, but I'd still like not to use any other binary here. :four_leaf_clover:

**Comment by IonicaBizau** [comment]
This would be cool to be implemented in `gh-cli-cal`: https://github.com/IonicaBizau/cli-gh-cal/issues/4.

**Comment by IonicaBizau** [comment]
`gh-cli-cal` returns the raw results and once #63 is fixed, we will be able to screenshot that page into an image.

**Comment by IonicaBizau** [comment]
I have a locally working solution. :tada: 

```sh
git-stats --raw | git-stats-html  > out.html && pageres out.html 775x250 && rm out.html
```

Generated the following image:

![out html-775x250](https://cloud.githubusercontent.com/assets/2864371/19626451/53902d0a-993b-11e6-8b25-fdaf7f9f302a.png)
