### ISSUE TITLE
Export to HTML

### ISSUE THREAD

**Issue by garygreen** [IonicaBizau/git-stats#63]
Would be nice to be able to export to HTML file like `git-stats --export=html > stats.html`

Ideally should be various exporter types, like image, html, text ansi, etc and people can add any that they like :-)

**Comment by IonicaBizau** [comment]
Nice idea! :sparkles: 

Regarding the image exporting, there is a similar issue: #50. Contributions are welcome! :smile:

**Comment by bratanon** [comment]
Yes! This would rock! Then you could create a cron job that runs once every day and use the exported image/HTML on your own webpage.

**Comment by IonicaBizau** [comment]
@bratanon Right now, priority number one is releasing `2.0.0`, and then I will work on these little issues. Maybe this week or the next one I will release the new version and if people will like it I will invest more time in adding new features. :smile:

**Comment by IonicaBizau** [comment]
Since 2.0.0, I'm moving to this issue. The first step would be to dump raw calendar data (in the `cli-gh-cal` format) to the stdout. Something like `git-stats --raw`. :sparkle:

**Comment by IonicaBizau** [comment]
It seems that @adros has done [something in this direction](https://github.com/adros/git-stats-html). :smile:

**Comment by IonicaBizau** [comment]
I'm on it.

**Comment by IonicaBizau** [comment]
@garygreen @bratanon See #50. This is kinda solved locally. I'm going to push the changes in the next couple of days. :smile:

**Comment by IonicaBizau** [comment]
Using [`git-stats-html`](https://github.com/IonicaBizau/git-stats-html) this is now possible. :tada: 

```sh
git-stats --raw | git-stats-html -o out.html
```
