### ISSUE TITLE
error Cannot find any emails. Specify them using -e

### ISSUE THREAD

**Issue by wouterds** [IonicaBizau/git-stats#67]
I have a big repo and I'm trying to generate the stats for it, but when I try to import the data it just throws this error message.

![Screenshot 1](https://up.kibakoapp.com/SMf84EfZpJ!#direct)

![Screenshot 2](https://up.kibakoapp.com/zHP97jvIfr!#direct)

![Screenshot 3](https://up.kibakoapp.com/3gjKZw9qhF!#direct)

**Comment by IonicaBizau** [comment]
Hey @wouterds,

I'm almost sure that the `$GIT_AUTHOR_EMAIL` is not set (you can confirm by running `echo $GIT_AUTHOR_EMAIL`).

The error message simply says to use the `-e` option. This should work:

```sh
$ git-stats-importer -e 'wouter.de.schuyter@gmail.com'
```

In case you have committed there with multiple emails, you can specify them too:

```sh
$ git-stats-importer -e 'wouter.de.schuyter@gmail.com, another@email.com'
```

Hope this helps! :dizzy:

**Comment by Pysis868** [comment]
Can we just have emails detected during scanning/importing of an existing local repo without needing to set an email list, especially for every repository we want to operate on?  That seems complicated and unnecessary.

**Comment by IonicaBizau** [comment]
@Pysis868 No, because `git-stats` is supposed to track *your* contributions. There is no way to guess your email.
