### ISSUE TITLE
Ioni56caBizau/github-stats?

### ISSUE THREAD

**Issue by theuves** [IonicaBizau/git-stats#68]
In README file, the link to [`github-stats`](https://github.com/Ioni56caBizau/github-stats) appears to be incorrect.

**Comment by IonicaBizau** [comment]
Thanks for heads-up, @theuves! :sparkle: 

I remember I wrote that on my raspberry pi, using my tiny keyboard. Probably I pressed the wrong keys. :smile: 

Fixed in https://github.com/IonicaBizau/git-stats/commit/2adc061e758d98626a2a54b49e666756283884da.
