### ISSUE TITLE
Set defaults in ~/.git-stats

### ISSUE THREAD

**Issue by rosstimson** [IonicaBizau/git-stats#7]
I recently tried git-stats and immediately got bitten with issue #2.  After seeing that file I assume that is a preferences file but I cannot find any docs about it.  Is it possible to set things like your preferred colours mode in this file, for instance I'd like to set the `--no-ansi` option to be the default?

**Comment by IonicaBizau** [comment]
In the `~/.git-stats` saves there all your git commits.

Currently there is no config file where we can save configs, but setting the `--no-ansi` by default is simple: `alias git-stats="git-stats --no-ansi"`.

**Comment by rosstimson** [comment]
Ah, sorry it seems I've misunderstood the purpose of that file then.

Cheers, I just didn't want to create yet another alias if there was a config file for purposes such as this.

**Comment by IonicaBizau** [comment]
This is now possible in `v2.0.0` branch (see #58). The following example will set the theme to no-ansi:

```json
{
  "theme": "NONE"
}
```
