### ISSUE TITLE
Usage not immediately clear

### ISSUE THREAD

**Issue by M-Zuber** [IonicaBizau/git-stats#78]
You have to get at least half way through the readme to understand that the tool has to be run from within a repository. (at least that is my feeling).

It would be nice to have  a section much earlier explaining that you have to move into a folder of a repo in order to get data.
Maybe a new section (the first obviously) under the [Usage heading](https://github.com/IonicaBizau/git-stats#usage)?

**Comment by IonicaBizau** [comment]
@M-Zuber That's very good point. In fact, I have the same feeling, but it's a good thing to get the feedback of a real user. :smile: 

I'm thinking that you maybe can add a section [before the *Installation*](https://github.com/IonicaBizau/git-stats/blob/0407c10643114ef2030edb2fa26fc8d912011111/package.json#L82) one summarizing the things a little bit from the user perspective. I tried my best to make it clear, but I'm a developer. :grin: 

You will have to [write it as JSON](http://ionicabizau.net/blog/27-how-to-convert-json-to-markdown-using-json2md) and generate it using `blah` (I will do that). If it's too complicated to write it as JSON, feel free to write markdown and I will convert it to JSON. :smile:

**Comment by M-Zuber** [comment]
I will try and do it later today.
The JSON should be just the new section?

**Comment by IonicaBizau** [comment]
@M-Zuber Yes, so something like this:

```js
...
        "[How to contribute](#how-to-contribute)"
        ]
      },
      { "h2": "The section you're adding" },
      { "p": "Something you want to write" }
    ],
    "installation_command": {
...
```

**Comment by M-Zuber** [comment]
```
{ "h2": "Quick Start" },
      { "p": "Once you've installed git-stats, run the command from within the project directory" }
```

Something like this.
I apologize, but currently I do not have the time to properly learn the syntax and add more information like 
```
//Go to project directory
cd path/to/your/repo
```
Also there seems to be a bug with the importer that I will try and file when I get the chance

**Comment by IonicaBizau** [comment]
We're now displaying the help output in README.md, which contains examples as well. Feel free to create a pull request for improving the docs. :memo:
