### ISSUE TITLE
Data is not displayed correctly

### ISSUE THREAD

**Issue by wb14123** [IonicaBizau/git-stats#81]
My contribute data is not correctly displayed: I can see some commits in `~/.git-stats` are not shown. For example, there are many commits since 2016, but the calendar just showed one of them:

![image](https://cloud.githubusercontent.com/assets/1906051/13373091/85a5061c-dd98-11e5-87ee-2315dbf9416d.png)

`~/.git-stats` is attached here: [git-stat.zip](https://github.com/IonicaBizau/git-stats/files/149340/git-stat.zip)

**Comment by IonicaBizau** [comment]
Looks like a migration script issue. It should be fixed in the latest version. Do `npm i git-stats@latest` to rerun the migration script. Thanks for the heads-up! :sparkle:
