### ISSUE TITLE
Error: Cannot find module '/usr/local/lib/node_modules/git-stats/scripts/migration/2.0.0.js'

### ISSUE THREAD

**Issue by michaeljcalkins** [IonicaBizau/git-stats#83]
![screen shot 2016-04-29 at 11 27 18 am](https://cloud.githubusercontent.com/assets/8272012/14925718/9a8a2b58-0dfd-11e6-8437-153e2ccfe442.png)

https://gist.github.com/michaeljcalkins/b77e42a224e2937ef01d2ad715b37fcf

**Comment by IonicaBizau** [comment]
Whoups, thanks for the heads up! In the latest release I whitelisted different files, but missed the `scripts`.

Should be fixed in #84. Try to install again.
