### ISSUE TITLE
Current Streak is Always Zero when --until Date Is Supplied

### ISSUE THREAD

**Issue by ode79** [IonicaBizau/git-stats#85]
Using `git-stats` and `git-stats --since <date>` on the commandline always gives me a correct number for the current streak.

But `git-stats --until <date>`, used with or without a `--since` date always has Current Streak set to zero.

I'm using node v4.4.3 on Linux and the v2.9.5 of git-stats installed from npm.

**Comment by IonicaBizau** [comment]
Hmm, interesting. Will check it out soon.

**Comment by IonicaBizau** [comment]
Actually this works as expected: you get the current streak at the specified date.
