### ISSUE TITLE
Installation Error:  Cannot read property 'commits' of undefined

### ISSUE THREAD

**Issue by wookayin** [IonicaBizau/git-stats#87]
* OS X (Homebrew)
* Node version : 6.0.0 (installed with homebrew, and the same happens for node 4.x, 5.x that I've tested)
```
$ ls -lh `which node`
lrwxr-xr-x  1 wookayin  admin    29B  5  4 00:02 /usr/local/bin/node -> ../Cellar/node/6.0.0/bin/node
```

Try to Install:
```
$ npm install -g git-stats
```

Error:
```
/usr/local/bin/git-stats -> /usr/local/lib/node_modules/git-stats/bin/git-stats

> git-stats@2.9.5 postinstall /usr/local/lib/node_modules/git-stats
> node scripts/migration/2.0.0.js

error EISDIR: illegal operation on a directory, read
/usr/local/lib/node_modules/git-stats/scripts/migration/2.0.0.js:23
    data.commits = data.commits || {};
                       ^

TypeError: Cannot read property 'commits' of undefined
    at migrate (/usr/local/lib/node_modules/git-stats/scripts/migration/2.0.0.js:23:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/git-stats/scripts/migration/2.0.0.js:38:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

Looks migration script is broken, so tried `npm install -g git-stats --ignore-scripts` either: then the `git-stats` binary is installed, but another exception is thrown:

```
/usr/local/lib/node_modules/git-stats/lib/index.js:501
            cDayObj = graph[cDay];
                           ^

TypeError: Cannot read property 'May 4, 2015' of undefined
```

I am delving into this for what is the cause; this would be just a simple report as of now.

Thanks,

**Comment by IonicaBizau** [comment]
For some reason it fails to read your home directory. Simply clone this repository and run the migration script manually... I'm not sure if there is a better solution. 💭

**Comment by wookayin** [comment]
@IonicaBizau The problem was that I had the `~/.git-stats` file which was empty. I am not sure why it had been corrupted; I just deleted it and it worked.

BTW, we can make the error message much more friendly. I will prepare a patch soon.
