### ISSUE TITLE
streak statistics in global view appear to be off

### ISSUE THREAD

**Issue by gleachkr** [IonicaBizau/git-stats#88]
Maybe I'm misunderstanding something, but the reported current and longest streaks for `git-stats -g` don't appear to be correct to me. 

In each of my repositories, longest streak is the same as current streak. Neither number looks right. The issue might be on display in the image displayed in the readme---the global stats produced by `git-stats --global` there don't seem to agree with the displayed calendar, and the longest streak is the same as the current streak.

**Comment by IonicaBizau** [comment]
@gleachkr Hmm, `git-stats -g` is showing the global stats of the current repository (all the collaborators). Currently I'm busy with other projects, but I'm happy to review contributions and merge them as long they   improve the project. :dizzy:

**Comment by IonicaBizau** [comment]
Like I mentioned, you're getting the current/longest streak for all the contributors in the project when using `-g`. This seems to work as expected.
