### ISSUE TITLE
cDayObj is not defined

### ISSUE THREAD

**Issue by gadelat** [IonicaBizau/git-stats#90]
> $  git-stats
> /usr/local/lib/node_modules/git-stats/lib/index.js:506
>             cDayObj = graph[cDay];
>                     ^
> 
> ReferenceError: cDayObj is not defined
>     at /usr/local/lib/node_modules/git-stats/lib/index.js:506:21
>     at GitStats.iterateDays (/usr/local/lib/node_modules/git-stats/lib/index.js:371:9)
>     at /usr/local/lib/node_modules/git-stats/lib/index.js:505:14
>     at /usr/local/lib/node_modules/git-stats/lib/index.js:415:9
>     at /usr/local/lib/node_modules/git-stats/lib/index.js:316:9
>     at /usr/local/lib/node_modules/git-stats/node_modules/r-json/lib/index.js:23:13
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by IonicaBizau** [comment]
I'm on it, thanks for heads'up.
