### ISSUE TITLE
Installation instructions do not work

### ISSUE THREAD

**Issue by lfjeff** [IonicaBizau/git-stats#95]
I installed the package like this (on Ubuntu 16.04):

`sudo npm i -g git-stats`

There were no errors and everything appeared to install OK.

Then I ran this script (as a regular user):
`curl -s https://raw.githubusercontent.com/IonicaBizau/git-stats/master/scripts/init-git-post-commit | bash`

When I try to run the script, the command cannot be found:
`$ git-stats`
`-su: git-stats: command not found`

What I am missing?  I'm not a node programmer, so something may be missing from my environment that node users assume is always there.

**Comment by IonicaBizau** [comment]
Don't run `npm` with `sudo`. Instead, configure `npm` like [here](https://github.com/IonicaBizau/dotfiles#npm-config).

Then, run `npm i -g git-stats`.
