### ISSUE TITLE
First day param does not affect the output

### ISSUE THREAD

**Issue by Baldrs** [IonicaBizau/git-stats#97]
See the screenshot for example output
![git-stats](https://cloud.githubusercontent.com/assets/814651/19247611/ad4d5770-8f34-11e6-8511-a52b484f1ba6.png)

> $ git-stats -v
> Git Stats 2.9.9

**Comment by IonicaBizau** [comment]
The first day will be always Sunday.

The option to set the first day was deprecated also in `cli-gh-cal`, therefore removed in `git-stats` too. /cc https://github.com/IonicaBizau/cli-gh-cal/pull/13
